version:  '3.7'
services:
    postgres:
        image: postgres:11.5-alpine
        restart: on-failure
        environment:
            POSTGRES_PASSWORD: toto
            POSTGRES_DB: toto
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        env_file:
            - .env
        environment:
            - PHP_IDE_CONFIG=serverName=accent_test_docker
            - XDEBUG_CONFIG=remote_host=docker.for.mac.localhost remote_port=9001
        volumes:
            - './:/var/www/app/current'
            - '../accent:/var/www/accent'
    nginx:
        image: nginx:1.17.2-alpine
        volumes:
            - './public/:/var/www/app/current'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '80:80'
        depends_on:
            - php
